export const APIREQUEST = 'APIREQUEST';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNOUT = 'SIGNOUT';

export const COLLECT_VISITOR_DATA = 'COLLECT_VISITOR_DATA';
export const RESET_COLLECT_VISITOR_DATA = 'RESET_COLLECT_VISITOR_DATA';
export const RESET_CREATED_VISITOR_DATA = 'RESET_CREATED_VISITOR_DATA';

export const VENDOR_ENTRY_REQUEST = 'VENDOR_ENTRY_REQUEST';
export const VENDOR_ENTRY_SUCCESS = 'VENDOR_ENTRY_SUCCESS';
export const VENDOR_ENTRY_ERROR = 'VENDOR_ENTRY_ERROR';

export const CREATE_VISITOR_REQUEST = 'CREATE_VISITOR_REQUEST';
export const CREATE_VISITOR_SUCCESS = 'CREATE_VISITOR_SUCCESS';
export const CREATE_VISITOR_ERROR = 'CREATE_VISITOR_ERROR';

export const GET_OWNER_REQUEST = 'GET_OWNER_REQUEST';
export const GET_OWNER_SUCCESS = 'GET_OWNER_SUCCESS';
export const GET_OWNER_ERROR = 'GET_OWNER_ERROR';
export const RESET_OWNER_DETAILS = 'RESET_OWNER_DETAILS';

export const GET_VISITORS_REQUEST = 'GET_VISITORS_REQUEST';
export const GET_VISITORS_SUCCESS = 'GET_VISITORS_SUCCESS';
export const GET_VISITORS_ERROR = 'GET_VISITORS_ERROR';
